#!/bin/bash

if [[ ! -z "$YCM_CONFIG_GEN_CXX_PASSTHROUGH" ]]; then
    # Cmake determines compiler properties by compiling a test file, so call clang for this case
    $YCM_CONFIG_GEN_CXX_PASSTHROUGH $@

elif [[ "$@" == "-v" ]]; then
    # Needed to enable clang-specific options for certain build systems (e.g. linux)
    echo "clang version 3.5.0 (fake toolchain)"

else
    echo "$@" >> $YCM_CONFIG_GEN_CXX_LOG
fi

